stages:
  download_data:
    cmd: python src/download_data.py
    outs:
      - data/
  train_model:
    cmd: python src/train_model.py
    deps:
      - data/
      - src/train_model.py
      - config.yaml
    outs:
      - models/yolov8n_blood_detection.pt